### ISSUE TITLE
Kapern sind als nicht vegetarisch gelistet

### ISSUE THREAD

**Issue by apriljunge** [LennyPenny/vegarando#5]
Eine Kaper ist die Blütenknospe des Kapernstrauchs [[Wikipedia](https://de.wikipedia.org/wiki/Echter_Kapernstrauch)], daher sollte diese aus meiner Sicht nicht in der Liste 'nicht vegatarisch' aka. bad auftauchen

**Comment by LukasKalbertodt** [comment]
Woops, da war ich vermutlich einfach nur doof. Vermutlich sollte dann auch "meeresfr" aus der Liste raus. Ich schätze die habe ich einfach nur mit aufgenommen, weil *ich* keine Meeresfrüchte mag, und habs dann vorm Veröffentlichen vergessen.

**Comment by apriljunge** [comment]
Nene. Kapern sind Pflanzen, also nicht tierisch. Vielleicht verwechselst du es mit Kaviar (Fischeier)?
Meeresfrüchte sind Tiere (Muscheln, Garnelen, ...). Die sollten also in der Liste bleiben.

Also aus meiner Sicht: Kapern raus, Meeresfrüchte sollten drin bleiben
